export type Permisions = {
  id: number;
  name: string;
};
export type Professional = {
  industry: any;
  id: number;
  first_name: string;
  last_name: string;
  date_of_birth: string;
  gender: string;
  email: string;
  account_type: string;
  created_at: string;
  private: number;
  is_followed: boolean;
  country: string;
  invite_link: string;
  phone_number: string;
  picture: string;
  token: string;
  total_followers: number;
  total_followings: number;
  total_posts: number;
  total_private_post_images: number;
  total_private_post_videos: number;
  total_public_post_images: number;
  total_public_post_videos: number;
  other_industry: string;
  is_2fa: string;
  profession: {
    id: number;
    profession: string;
    work_experience: null | string;
    total_work_experience: string;
    linkedin: null | string;
    facebook: null | string;
    instagram: null | string;
    tiktok: null | string;
    twitter: null | string;
    website: null | string;
    youtube: null | string;
  };
  profile: {
    id: number;
    phone_number: string;
    picture: string;
    bio: string | null | undefined;
    country: string;
    profile: string;
    invite_link: string;
  };
  total_books: number;
  total_films: number;
  total_photography: number;
  total_articles: number;
  total_exhibition: number;
  total_qualifications: number;
  total_other: number;
  total_awards: number;
  total_nominations: number;
  user_permissions: Permisions[];
  user_role: {
    id: number;
    name: string;
    updated_at: string;
  };
  user_token: string;
};
