export const SESSION_USER = "SESSION_USER";
export const USER_TOKEN = "USER_TOKEN";

export const allowedUsers = [
  "agbenuwisdoms@gmail.com",
  "azubirepeter@gmail.com",
  "phil@gmail.com",
  "letiviapp@gmail.com",
  "charlesagbemashior@gmail.com",
  "thinkactivemedia@gmail.com",
];

export const Countries = [
  "Afghanistan",
  "Åland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo (Republic of the)",
  "Congo (Democratic Republic of the)",
  "Cook Islands",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Vatican City State",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (Democratic People's Republic of)",
  "Korea (Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia (the former Yugoslav Republic of)",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  " Pakistan",
  " Palau",
  " Palestine, State of",
  " Panama",
  " Papua New Guinea",
  " Paraguay",
  " Peru",
  " Philippines",
  " Pitcairn",
  " Poland",
  " Portugal",
  " Puerto Rico",
  " Qatar",
  " Réunion",
  " Romania",
  " Russian Federation",
  " Rwanda",
  " Saint Barthélemy",
  " Saint Helena, Ascension and Tristan da Cunha",
  " Saint Kitts and Nevis",
  " Saint Lucia",
  "Saint Martin (French part)",
  " Saint Pierre and Miquelon",
  " Saint Vincent and the Grenadines",
  " Samoa",
  " San Marino",
  " Sao Tome and Principe",
  "Saudi Arabia",
  " Senegal",
  "Serbia",
  " Seychelles",
  " Sierra Leone",
  " Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom of Great Britain and Northern Ireland",
  "United States Minor Outlying Islands",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Vietnam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const Professions = [
  "Farmer",
  "Teacher",
  "Software Developer",
  "Director",
  "Model",
  "Doctor",
  "Engineer",
  "Artist",
  "Chef",
  "Journalist",
  "Photographer",
  "Pilot",
  "Lawyer",
  "Dancer",
  "Architect",
  "Scientist",
  "Graphic Designer",
  "Nurse",
  "Musician",
  "Designer",
  "Entertainer",
  "Police Officer",
  // Add more professions as needed
];

// countries.ts - Comprehensive list of world countries with ISO codes and flag URLs

export interface Country {
  id: string; // ISO 2-letter country code
  name: string; // Country name
  icon?: string; // URL to flag image
  dialCode?: string; // International dialing code (optional)
}

export const countriesList: Country[] = [
  {
    id: "af",
    name: "Afghanistan",
    icon: "https://flagcdn.com/w40/af.png",
    dialCode: "+93",
  },
  {
    id: "al",
    name: "Albania",
    icon: "https://flagcdn.com/w40/al.png",
    dialCode: "+355",
  },
  {
    id: "dz",
    name: "Algeria",
    icon: "https://flagcdn.com/w40/dz.png",
    dialCode: "+213",
  },
  {
    id: "as",
    name: "American Samoa",
    icon: "https://flagcdn.com/w40/as.png",
    dialCode: "+1684",
  },
  {
    id: "ad",
    name: "Andorra",
    icon: "https://flagcdn.com/w40/ad.png",
    dialCode: "+376",
  },
  {
    id: "ao",
    name: "Angola",
    icon: "https://flagcdn.com/w40/ao.png",
    dialCode: "+244",
  },
  {
    id: "ai",
    name: "Anguilla",
    icon: "https://flagcdn.com/w40/ai.png",
    dialCode: "+1264",
  },
  { id: "aq", name: "Antarctica", icon: "https://flagcdn.com/w40/aq.png" },
  {
    id: "ag",
    name: "Antigua and Barbuda",
    icon: "https://flagcdn.com/w40/ag.png",
    dialCode: "+1268",
  },
  {
    id: "ar",
    name: "Argentina",
    icon: "https://flagcdn.com/w40/ar.png",
    dialCode: "+54",
  },
  {
    id: "am",
    name: "Armenia",
    icon: "https://flagcdn.com/w40/am.png",
    dialCode: "+374",
  },
  {
    id: "aw",
    name: "Aruba",
    icon: "https://flagcdn.com/w40/aw.png",
    dialCode: "+297",
  },
  {
    id: "au",
    name: "Australia",
    icon: "https://flagcdn.com/w40/au.png",
    dialCode: "+61",
  },
  {
    id: "at",
    name: "Austria",
    icon: "https://flagcdn.com/w40/at.png",
    dialCode: "+43",
  },
  {
    id: "az",
    name: "Azerbaijan",
    icon: "https://flagcdn.com/w40/az.png",
    dialCode: "+994",
  },
  {
    id: "bs",
    name: "Bahamas",
    icon: "https://flagcdn.com/w40/bs.png",
    dialCode: "+1242",
  },
  {
    id: "bh",
    name: "Bahrain",
    icon: "https://flagcdn.com/w40/bh.png",
    dialCode: "+973",
  },
  {
    id: "bd",
    name: "Bangladesh",
    icon: "https://flagcdn.com/w40/bd.png",
    dialCode: "+880",
  },
  {
    id: "bb",
    name: "Barbados",
    icon: "https://flagcdn.com/w40/bb.png",
    dialCode: "+1246",
  },
  {
    id: "by",
    name: "Belarus",
    icon: "https://flagcdn.com/w40/by.png",
    dialCode: "+375",
  },
  {
    id: "be",
    name: "Belgium",
    icon: "https://flagcdn.com/w40/be.png",
    dialCode: "+32",
  },
  {
    id: "bz",
    name: "Belize",
    icon: "https://flagcdn.com/w40/bz.png",
    dialCode: "+501",
  },
  {
    id: "bj",
    name: "Benin",
    icon: "https://flagcdn.com/w40/bj.png",
    dialCode: "+229",
  },
  {
    id: "bm",
    name: "Bermuda",
    icon: "https://flagcdn.com/w40/bm.png",
    dialCode: "+1441",
  },
  {
    id: "bt",
    name: "Bhutan",
    icon: "https://flagcdn.com/w40/bt.png",
    dialCode: "+975",
  },
  {
    id: "bo",
    name: "Bolivia",
    icon: "https://flagcdn.com/w40/bo.png",
    dialCode: "+591",
  },
  {
    id: "ba",
    name: "Bosnia and Herzegovina",
    icon: "https://flagcdn.com/w40/ba.png",
    dialCode: "+387",
  },
  {
    id: "bw",
    name: "Botswana",
    icon: "https://flagcdn.com/w40/bw.png",
    dialCode: "+267",
  },
  {
    id: "br",
    name: "Brazil",
    icon: "https://flagcdn.com/w40/br.png",
    dialCode: "+55",
  },
  {
    id: "io",
    name: "British Indian Ocean Territory",
    icon: "https://flagcdn.com/w40/io.png",
    dialCode: "+246",
  },
  {
    id: "vg",
    name: "British Virgin Islands",
    icon: "https://flagcdn.com/w40/vg.png",
    dialCode: "+1284",
  },
  {
    id: "bn",
    name: "Brunei",
    icon: "https://flagcdn.com/w40/bn.png",
    dialCode: "+673",
  },
  {
    id: "bg",
    name: "Bulgaria",
    icon: "https://flagcdn.com/w40/bg.png",
    dialCode: "+359",
  },
  {
    id: "bf",
    name: "Burkina Faso",
    icon: "https://flagcdn.com/w40/bf.png",
    dialCode: "+226",
  },
  {
    id: "bi",
    name: "Burundi",
    icon: "https://flagcdn.com/w40/bi.png",
    dialCode: "+257",
  },
  {
    id: "kh",
    name: "Cambodia",
    icon: "https://flagcdn.com/w40/kh.png",
    dialCode: "+855",
  },
  {
    id: "cm",
    name: "Cameroon",
    icon: "https://flagcdn.com/w40/cm.png",
    dialCode: "+237",
  },
  {
    id: "ca",
    name: "Canada",
    icon: "https://flagcdn.com/w40/ca.png",
    dialCode: "+1",
  },
  {
    id: "cv",
    name: "Cape Verde",
    icon: "https://flagcdn.com/w40/cv.png",
    dialCode: "+238",
  },
  {
    id: "ky",
    name: "Cayman Islands",
    icon: "https://flagcdn.com/w40/ky.png",
    dialCode: "+1345",
  },
  {
    id: "cf",
    name: "Central African Republic",
    icon: "https://flagcdn.com/w40/cf.png",
    dialCode: "+236",
  },
  {
    id: "td",
    name: "Chad",
    icon: "https://flagcdn.com/w40/td.png",
    dialCode: "+235",
  },
  {
    id: "cl",
    name: "Chile",
    icon: "https://flagcdn.com/w40/cl.png",
    dialCode: "+56",
  },
  {
    id: "cn",
    name: "China",
    icon: "https://flagcdn.com/w40/cn.png",
    dialCode: "+86",
  },
  {
    id: "cx",
    name: "Christmas Island",
    icon: "https://flagcdn.com/w40/cx.png",
    dialCode: "+61",
  },
  {
    id: "cc",
    name: "Cocos Islands",
    icon: "https://flagcdn.com/w40/cc.png",
    dialCode: "+61",
  },
  {
    id: "co",
    name: "Colombia",
    icon: "https://flagcdn.com/w40/co.png",
    dialCode: "+57",
  },
  {
    id: "km",
    name: "Comoros",
    icon: "https://flagcdn.com/w40/km.png",
    dialCode: "+269",
  },
  {
    id: "ck",
    name: "Cook Islands",
    icon: "https://flagcdn.com/w40/ck.png",
    dialCode: "+682",
  },
  {
    id: "cr",
    name: "Costa Rica",
    icon: "https://flagcdn.com/w40/cr.png",
    dialCode: "+506",
  },
  {
    id: "hr",
    name: "Croatia",
    icon: "https://flagcdn.com/w40/hr.png",
    dialCode: "+385",
  },
  {
    id: "cu",
    name: "Cuba",
    icon: "https://flagcdn.com/w40/cu.png",
    dialCode: "+53",
  },
  {
    id: "cw",
    name: "Curaçao",
    icon: "https://flagcdn.com/w40/cw.png",
    dialCode: "+599",
  },
  {
    id: "cy",
    name: "Cyprus",
    icon: "https://flagcdn.com/w40/cy.png",
    dialCode: "+357",
  },
  {
    id: "cz",
    name: "Czech Republic",
    icon: "https://flagcdn.com/w40/cz.png",
    dialCode: "+420",
  },
  {
    id: "cd",
    name: "Democratic Republic of the Congo",
    icon: "https://flagcdn.com/w40/cd.png",
    dialCode: "+243",
  },
  {
    id: "dk",
    name: "Denmark",
    icon: "https://flagcdn.com/w40/dk.png",
    dialCode: "+45",
  },
  {
    id: "dj",
    name: "Djibouti",
    icon: "https://flagcdn.com/w40/dj.png",
    dialCode: "+253",
  },
  {
    id: "dm",
    name: "Dominica",
    icon: "https://flagcdn.com/w40/dm.png",
    dialCode: "+1767",
  },
  {
    id: "do",
    name: "Dominican Republic",
    icon: "https://flagcdn.com/w40/do.png",
    dialCode: "+1809",
  },
  {
    id: "tl",
    name: "East Timor",
    icon: "https://flagcdn.com/w40/tl.png",
    dialCode: "+670",
  },
  {
    id: "ec",
    name: "Ecuador",
    icon: "https://flagcdn.com/w40/ec.png",
    dialCode: "+593",
  },
  {
    id: "eg",
    name: "Egypt",
    icon: "https://flagcdn.com/w40/eg.png",
    dialCode: "+20",
  },
  {
    id: "sv",
    name: "El Salvador",
    icon: "https://flagcdn.com/w40/sv.png",
    dialCode: "+503",
  },
  {
    id: "gq",
    name: "Equatorial Guinea",
    icon: "https://flagcdn.com/w40/gq.png",
    dialCode: "+240",
  },
  {
    id: "er",
    name: "Eritrea",
    icon: "https://flagcdn.com/w40/er.png",
    dialCode: "+291",
  },
  {
    id: "ee",
    name: "Estonia",
    icon: "https://flagcdn.com/w40/ee.png",
    dialCode: "+372",
  },
  {
    id: "et",
    name: "Ethiopia",
    icon: "https://flagcdn.com/w40/et.png",
    dialCode: "+251",
  },
  {
    id: "fk",
    name: "Falkland Islands",
    icon: "https://flagcdn.com/w40/fk.png",
    dialCode: "+500",
  },
  {
    id: "fo",
    name: "Faroe Islands",
    icon: "https://flagcdn.com/w40/fo.png",
    dialCode: "+298",
  },
  {
    id: "fj",
    name: "Fiji",
    icon: "https://flagcdn.com/w40/fj.png",
    dialCode: "+679",
  },
  {
    id: "fi",
    name: "Finland",
    icon: "https://flagcdn.com/w40/fi.png",
    dialCode: "+358",
  },
  {
    id: "fr",
    name: "France",
    icon: "https://flagcdn.com/w40/fr.png",
    dialCode: "+33",
  },
  {
    id: "gf",
    name: "French Guiana",
    icon: "https://flagcdn.com/w40/gf.png",
    dialCode: "+594",
  },
  {
    id: "pf",
    name: "French Polynesia",
    icon: "https://flagcdn.com/w40/pf.png",
    dialCode: "+689",
  },
  {
    id: "ga",
    name: "Gabon",
    icon: "https://flagcdn.com/w40/ga.png",
    dialCode: "+241",
  },
  {
    id: "gm",
    name: "Gambia",
    icon: "https://flagcdn.com/w40/gm.png",
    dialCode: "+220",
  },
  {
    id: "ge",
    name: "Georgia",
    icon: "https://flagcdn.com/w40/ge.png",
    dialCode: "+995",
  },
  {
    id: "de",
    name: "Germany",
    icon: "https://flagcdn.com/w40/de.png",
    dialCode: "+49",
  },
  {
    id: "gh",
    name: "Ghana",
    icon: "https://flagcdn.com/w40/gh.png",
    dialCode: "+233",
  },
  {
    id: "gi",
    name: "Gibraltar",
    icon: "https://flagcdn.com/w40/gi.png",
    dialCode: "+350",
  },
  {
    id: "gr",
    name: "Greece",
    icon: "https://flagcdn.com/w40/gr.png",
    dialCode: "+30",
  },
  {
    id: "gl",
    name: "Greenland",
    icon: "https://flagcdn.com/w40/gl.png",
    dialCode: "+299",
  },
  {
    id: "gd",
    name: "Grenada",
    icon: "https://flagcdn.com/w40/gd.png",
    dialCode: "+1473",
  },
  {
    id: "gp",
    name: "Guadeloupe",
    icon: "https://flagcdn.com/w40/gp.png",
    dialCode: "+590",
  },
  {
    id: "gu",
    name: "Guam",
    icon: "https://flagcdn.com/w40/gu.png",
    dialCode: "+1671",
  },
  {
    id: "gt",
    name: "Guatemala",
    icon: "https://flagcdn.com/w40/gt.png",
    dialCode: "+502",
  },
  {
    id: "gg",
    name: "Guernsey",
    icon: "https://flagcdn.com/w40/gg.png",
    dialCode: "+44",
  },
  {
    id: "gn",
    name: "Guinea",
    icon: "https://flagcdn.com/w40/gn.png",
    dialCode: "+224",
  },
  {
    id: "gw",
    name: "Guinea-Bissau",
    icon: "https://flagcdn.com/w40/gw.png",
    dialCode: "+245",
  },
  {
    id: "gy",
    name: "Guyana",
    icon: "https://flagcdn.com/w40/gy.png",
    dialCode: "+592",
  },
  {
    id: "ht",
    name: "Haiti",
    icon: "https://flagcdn.com/w40/ht.png",
    dialCode: "+509",
  },
  {
    id: "hn",
    name: "Honduras",
    icon: "https://flagcdn.com/w40/hn.png",
    dialCode: "+504",
  },
  {
    id: "hk",
    name: "Hong Kong",
    icon: "https://flagcdn.com/w40/hk.png",
    dialCode: "+852",
  },
  {
    id: "hu",
    name: "Hungary",
    icon: "https://flagcdn.com/w40/hu.png",
    dialCode: "+36",
  },
  {
    id: "is",
    name: "Iceland",
    icon: "https://flagcdn.com/w40/is.png",
    dialCode: "+354",
  },
  {
    id: "in",
    name: "India",
    icon: "https://flagcdn.com/w40/in.png",
    dialCode: "+91",
  },
  {
    id: "id",
    name: "Indonesia",
    icon: "https://flagcdn.com/w40/id.png",
    dialCode: "+62",
  },
  {
    id: "ir",
    name: "Iran",
    icon: "https://flagcdn.com/w40/ir.png",
    dialCode: "+98",
  },
  {
    id: "iq",
    name: "Iraq",
    icon: "https://flagcdn.com/w40/iq.png",
    dialCode: "+964",
  },
  {
    id: "ie",
    name: "Ireland",
    icon: "https://flagcdn.com/w40/ie.png",
    dialCode: "+353",
  },
  {
    id: "im",
    name: "Isle of Man",
    icon: "https://flagcdn.com/w40/im.png",
    dialCode: "+44",
  },
  {
    id: "il",
    name: "Israel",
    icon: "https://flagcdn.com/w40/il.png",
    dialCode: "+972",
  },
  {
    id: "it",
    name: "Italy",
    icon: "https://flagcdn.com/w40/it.png",
    dialCode: "+39",
  },
  {
    id: "ci",
    name: "Ivory Coast",
    icon: "https://flagcdn.com/w40/ci.png",
    dialCode: "+225",
  },
  {
    id: "jm",
    name: "Jamaica",
    icon: "https://flagcdn.com/w40/jm.png",
    dialCode: "+1876",
  },
  {
    id: "jp",
    name: "Japan",
    icon: "https://flagcdn.com/w40/jp.png",
    dialCode: "+81",
  },
  {
    id: "je",
    name: "Jersey",
    icon: "https://flagcdn.com/w40/je.png",
    dialCode: "+44",
  },
  {
    id: "jo",
    name: "Jordan",
    icon: "https://flagcdn.com/w40/jo.png",
    dialCode: "+962",
  },
  {
    id: "kz",
    name: "Kazakhstan",
    icon: "https://flagcdn.com/w40/kz.png",
    dialCode: "+7",
  },
  {
    id: "ke",
    name: "Kenya",
    icon: "https://flagcdn.com/w40/ke.png",
    dialCode: "+254",
  },
  {
    id: "ki",
    name: "Kiribati",
    icon: "https://flagcdn.com/w40/ki.png",
    dialCode: "+686",
  },
  {
    id: "xk",
    name: "Kosovo",
    icon: "https://flagcdn.com/w40/xk.png",
    dialCode: "+383",
  },
  {
    id: "kw",
    name: "Kuwait",
    icon: "https://flagcdn.com/w40/kw.png",
    dialCode: "+965",
  },
  {
    id: "kg",
    name: "Kyrgyzstan",
    icon: "https://flagcdn.com/w40/kg.png",
    dialCode: "+996",
  },
  {
    id: "la",
    name: "Laos",
    icon: "https://flagcdn.com/w40/la.png",
    dialCode: "+856",
  },
  {
    id: "lv",
    name: "Latvia",
    icon: "https://flagcdn.com/w40/lv.png",
    dialCode: "+371",
  },
  {
    id: "lb",
    name: "Lebanon",
    icon: "https://flagcdn.com/w40/lb.png",
    dialCode: "+961",
  },
  {
    id: "ls",
    name: "Lesotho",
    icon: "https://flagcdn.com/w40/ls.png",
    dialCode: "+266",
  },
  {
    id: "lr",
    name: "Liberia",
    icon: "https://flagcdn.com/w40/lr.png",
    dialCode: "+231",
  },
  {
    id: "ly",
    name: "Libya",
    icon: "https://flagcdn.com/w40/ly.png",
    dialCode: "+218",
  },
  {
    id: "li",
    name: "Liechtenstein",
    icon: "https://flagcdn.com/w40/li.png",
    dialCode: "+423",
  },
  {
    id: "lt",
    name: "Lithuania",
    icon: "https://flagcdn.com/w40/lt.png",
    dialCode: "+370",
  },
  {
    id: "lu",
    name: "Luxembourg",
    icon: "https://flagcdn.com/w40/lu.png",
    dialCode: "+352",
  },
  {
    id: "mo",
    name: "Macau",
    icon: "https://flagcdn.com/w40/mo.png",
    dialCode: "+853",
  },
  {
    id: "mk",
    name: "Macedonia",
    icon: "https://flagcdn.com/w40/mk.png",
    dialCode: "+389",
  },
  {
    id: "mg",
    name: "Madagascar",
    icon: "https://flagcdn.com/w40/mg.png",
    dialCode: "+261",
  },
  {
    id: "mw",
    name: "Malawi",
    icon: "https://flagcdn.com/w40/mw.png",
    dialCode: "+265",
  },
  {
    id: "my",
    name: "Malaysia",
    icon: "https://flagcdn.com/w40/my.png",
    dialCode: "+60",
  },
  {
    id: "mv",
    name: "Maldives",
    icon: "https://flagcdn.com/w40/mv.png",
    dialCode: "+960",
  },
  {
    id: "ml",
    name: "Mali",
    icon: "https://flagcdn.com/w40/ml.png",
    dialCode: "+223",
  },
  {
    id: "mt",
    name: "Malta",
    icon: "https://flagcdn.com/w40/mt.png",
    dialCode: "+356",
  },
  {
    id: "mh",
    name: "Marshall Islands",
    icon: "https://flagcdn.com/w40/mh.png",
    dialCode: "+692",
  },
  {
    id: "mq",
    name: "Martinique",
    icon: "https://flagcdn.com/w40/mq.png",
    dialCode: "+596",
  },
  {
    id: "mr",
    name: "Mauritania",
    icon: "https://flagcdn.com/w40/mr.png",
    dialCode: "+222",
  },
  {
    id: "mu",
    name: "Mauritius",
    icon: "https://flagcdn.com/w40/mu.png",
    dialCode: "+230",
  },
  {
    id: "yt",
    name: "Mayotte",
    icon: "https://flagcdn.com/w40/yt.png",
    dialCode: "+262",
  },
  {
    id: "mx",
    name: "Mexico",
    icon: "https://flagcdn.com/w40/mx.png",
    dialCode: "+52",
  },
  {
    id: "fm",
    name: "Micronesia",
    icon: "https://flagcdn.com/w40/fm.png",
    dialCode: "+691",
  },
  {
    id: "md",
    name: "Moldova",
    icon: "https://flagcdn.com/w40/md.png",
    dialCode: "+373",
  },
  {
    id: "mc",
    name: "Monaco",
    icon: "https://flagcdn.com/w40/mc.png",
    dialCode: "+377",
  },
  {
    id: "mn",
    name: "Mongolia",
    icon: "https://flagcdn.com/w40/mn.png",
    dialCode: "+976",
  },
  {
    id: "me",
    name: "Montenegro",
    icon: "https://flagcdn.com/w40/me.png",
    dialCode: "+382",
  },
  {
    id: "ms",
    name: "Montserrat",
    icon: "https://flagcdn.com/w40/ms.png",
    dialCode: "+1664",
  },
  {
    id: "ma",
    name: "Morocco",
    icon: "https://flagcdn.com/w40/ma.png",
    dialCode: "+212",
  },
  {
    id: "mz",
    name: "Mozambique",
    icon: "https://flagcdn.com/w40/mz.png",
    dialCode: "+258",
  },
  {
    id: "mm",
    name: "Myanmar",
    icon: "https://flagcdn.com/w40/mm.png",
    dialCode: "+95",
  },
  {
    id: "na",
    name: "Namibia",
    icon: "https://flagcdn.com/w40/na.png",
    dialCode: "+264",
  },
  {
    id: "nr",
    name: "Nauru",
    icon: "https://flagcdn.com/w40/nr.png",
    dialCode: "+674",
  },
  {
    id: "np",
    name: "Nepal",
    icon: "https://flagcdn.com/w40/np.png",
    dialCode: "+977",
  },
  {
    id: "nl",
    name: "Netherlands",
    icon: "https://flagcdn.com/w40/nl.png",
    dialCode: "+31",
  },
  {
    id: "nc",
    name: "New Caledonia",
    icon: "https://flagcdn.com/w40/nc.png",
    dialCode: "+687",
  },
  {
    id: "nz",
    name: "New Zealand",
    icon: "https://flagcdn.com/w40/nz.png",
    dialCode: "+64",
  },
  {
    id: "ni",
    name: "Nicaragua",
    icon: "https://flagcdn.com/w40/ni.png",
    dialCode: "+505",
  },
  {
    id: "ne",
    name: "Niger",
    icon: "https://flagcdn.com/w40/ne.png",
    dialCode: "+227",
  },
  {
    id: "ng",
    name: "Nigeria",
    icon: "https://flagcdn.com/w40/ng.png",
    dialCode: "+234",
  },
  {
    id: "nu",
    name: "Niue",
    icon: "https://flagcdn.com/w40/nu.png",
    dialCode: "+683",
  },
  {
    id: "nf",
    name: "Norfolk Island",
    icon: "https://flagcdn.com/w40/nf.png",
    dialCode: "+672",
  },
  {
    id: "kp",
    name: "North Korea",
    icon: "https://flagcdn.com/w40/kp.png",
    dialCode: "+850",
  },
  {
    id: "mp",
    name: "Northern Mariana Islands",
    icon: "https://flagcdn.com/w40/mp.png",
    dialCode: "+1670",
  },
  {
    id: "no",
    name: "Norway",
    icon: "https://flagcdn.com/w40/no.png",
    dialCode: "+47",
  },
  {
    id: "om",
    name: "Oman",
    icon: "https://flagcdn.com/w40/om.png",
    dialCode: "+968",
  },
  {
    id: "pk",
    name: "Pakistan",
    icon: "https://flagcdn.com/w40/pk.png",
    dialCode: "+92",
  },
  {
    id: "pw",
    name: "Palau",
    icon: "https://flagcdn.com/w40/pw.png",
    dialCode: "+680",
  },
  {
    id: "ps",
    name: "Palestine",
    icon: "https://flagcdn.com/w40/ps.png",
    dialCode: "+970",
  },
  {
    id: "pa",
    name: "Panama",
    icon: "https://flagcdn.com/w40/pa.png",
    dialCode: "+507",
  },
  {
    id: "pg",
    name: "Papua New Guinea",
    icon: "https://flagcdn.com/w40/pg.png",
    dialCode: "+675",
  },
  {
    id: "py",
    name: "Paraguay",
    icon: "https://flagcdn.com/w40/py.png",
    dialCode: "+595",
  },
  {
    id: "pe",
    name: "Peru",
    icon: "https://flagcdn.com/w40/pe.png",
    dialCode: "+51",
  },
  {
    id: "ph",
    name: "Philippines",
    icon: "https://flagcdn.com/w40/ph.png",
    dialCode: "+63",
  },
  {
    id: "pn",
    name: "Pitcairn",
    icon: "https://flagcdn.com/w40/pn.png",
    dialCode: "+64",
  },
  {
    id: "pl",
    name: "Poland",
    icon: "https://flagcdn.com/w40/pl.png",
    dialCode: "+48",
  },
  {
    id: "pt",
    name: "Portugal",
    icon: "https://flagcdn.com/w40/pt.png",
    dialCode: "+351",
  },
  {
    id: "pr",
    name: "Puerto Rico",
    icon: "https://flagcdn.com/w40/pr.png",
    dialCode: "+1787",
  },
  {
    id: "qa",
    name: "Qatar",
    icon: "https://flagcdn.com/w40/qa.png",
    dialCode: "+974",
  },
  {
    id: "cg",
    name: "Republic of the Congo",
    icon: "https://flagcdn.com/w40/cg.png",
    dialCode: "+242",
  },
  {
    id: "re",
    name: "Reunion",
    icon: "https://flagcdn.com/w40/re.png",
    dialCode: "+262",
  },
  {
    id: "ro",
    name: "Romania",
    icon: "https://flagcdn.com/w40/ro.png",
    dialCode: "+40",
  },
  {
    id: "ru",
    name: "Russia",
    icon: "https://flagcdn.com/w40/ru.png",
    dialCode: "+7",
  },
  {
    id: "rw",
    name: "Rwanda",
    icon: "https://flagcdn.com/w40/rw.png",
    dialCode: "+250",
  },
  {
    id: "bl",
    name: "Saint Barthélemy",
    icon: "https://flagcdn.com/w40/bl.png",
    dialCode: "+590",
  },
  {
    id: "sh",
    name: "Saint Helena",
    icon: "https://flagcdn.com/w40/sh.png",
    dialCode: "+290",
  },
  {
    id: "kn",
    name: "Saint Kitts and Nevis",
    icon: "https://flagcdn.com/w40/kn.png",
    dialCode: "+1869",
  },
  {
    id: "lc",
    name: "Saint Lucia",
    icon: "https://flagcdn.com/w40/lc.png",
    dialCode: "+1758",
  },
  {
    id: "mf",
    name: "Saint Martin",
    icon: "https://flagcdn.com/w40/mf.png",
    dialCode: "+590",
  },
  {
    id: "pm",
    name: "Saint Pierre and Miquelon",
    icon: "https://flagcdn.com/w40/pm.png",
    dialCode: "+508",
  },
  {
    id: "vc",
    name: "Saint Vincent and the Grenadines",
    icon: "https://flagcdn.com/w40/vc.png",
    dialCode: "+1784",
  },
  {
    id: "ws",
    name: "Samoa",
    icon: "https://flagcdn.com/w40/ws.png",
    dialCode: "+685",
  },
  {
    id: "sm",
    name: "San Marino",
    icon: "https://flagcdn.com/w40/sm.png",
    dialCode: "+378",
  },
  {
    id: "st",
    name: "São Tomé and Príncipe",
    icon: "https://flagcdn.com/w40/st.png",
    dialCode: "+239",
  },
  {
    id: "sa",
    name: "Saudi Arabia",
    icon: "https://flagcdn.com/w40/sa.png",
    dialCode: "+966",
  },
  {
    id: "sn",
    name: "Senegal",
    icon: "https://flagcdn.com/w40/sn.png",
    dialCode: "+221",
  },
  {
    id: "rs",
    name: "Serbia",
    icon: "https://flagcdn.com/w40/rs.png",
    dialCode: "+381",
  },
  {
    id: "sc",
    name: "Seychelles",
    icon: "https://flagcdn.com/w40/sc.png",
    dialCode: "+248",
  },
  {
    id: "sl",
    name: "Sierra Leone",
    icon: "https://flagcdn.com/w40/sl.png",
    dialCode: "+232",
  },
  {
    id: "sg",
    name: "Singapore",
    icon: "https://flagcdn.com/w40/sg.png",
    dialCode: "+65",
  },
  {
    id: "sx",
    name: "Sint Maarten",
    icon: "https://flagcdn.com/w40/sx.png",
    dialCode: "+1721",
  },
  {
    id: "sk",
    name: "Slovakia",
    icon: "https://flagcdn.com/w40/sk.png",
    dialCode: "+421",
  },
  {
    id: "si",
    name: "Slovenia",
    icon: "https://flagcdn.com/w40/si.png",
    dialCode: "+386",
  },
  {
    id: "sb",
    name: "Solomon Islands",
    icon: "https://flagcdn.com/w40/sb.png",
    dialCode: "+677",
  },
  {
    id: "so",
    name: "Somalia",
    icon: "https://flagcdn.com/w40/so.png",
    dialCode: "+252",
  },
  {
    id: "za",
    name: "South Africa",
    icon: "https://flagcdn.com/w40/za.png",
    dialCode: "+27",
  },
  {
    id: "kr",
    name: "South Korea",
    icon: "https://flagcdn.com/w40/kr.png",
    dialCode: "+82",
  },
  {
    id: "ss",
    name: "South Sudan",
    icon: "https://flagcdn.com/w40/ss.png",
    dialCode: "+211",
  },
  {
    id: "es",
    name: "Spain",
    icon: "https://flagcdn.com/w40/es.png",
    dialCode: "+34",
  },
  {
    id: "lk",
    name: "Sri Lanka",
    icon: "https://flagcdn.com/w40/lk.png",
    dialCode: "+94",
  },
  {
    id: "sd",
    name: "Sudan",
    icon: "https://flagcdn.com/w40/sd.png",
    dialCode: "+249",
  },
  {
    id: "sr",
    name: "Suriname",
    icon: "https://flagcdn.com/w40/sr.png",
    dialCode: "+597",
  },
  {
    id: "sz",
    name: "Swaziland",
    icon: "https://flagcdn.com/w40/sz.png",
    dialCode: "+268",
  },
  {
    id: "se",
    name: "Sweden",
    icon: "https://flagcdn.com/w40/se.png",
    dialCode: "+46",
  },
  {
    id: "ch",
    name: "Switzerland",
    icon: "https://flagcdn.com/w40/ch.png",
    dialCode: "+41",
  },
  {
    id: "sy",
    name: "Syria",
    icon: "https://flagcdn.com/w40/sy.png",
    dialCode: "+963",
  },
  {
    id: "tw",
    name: "Taiwan",
    icon: "https://flagcdn.com/w40/tw.png",
    dialCode: "+886",
  },
  {
    id: "tj",
    name: "Tajikistan",
    icon: "https://flagcdn.com/w40/tj.png",
    dialCode: "+992",
  },
  {
    id: "tz",
    name: "Tanzania",
    icon: "https://flagcdn.com/w40/tz.png",
    dialCode: "+255",
  },
  {
    id: "th",
    name: "Thailand",
    icon: "https://flagcdn.com/w40/th.png",
    dialCode: "+66",
  },
  {
    id: "tg",
    name: "Togo",
    icon: "https://flagcdn.com/w40/tg.png",
    dialCode: "+228",
  },
  {
    id: "tk",
    name: "Tokelau",
    icon: "https://flagcdn.com/w40/tk.png",
    dialCode: "+690",
  },
  {
    id: "to",
    name: "Tonga",
    icon: "https://flagcdn.com/w40/to.png",
    dialCode: "+676",
  },
  {
    id: "tt",
    name: "Trinidad and Tobago",
    icon: "https://flagcdn.com/w40/tt.png",
    dialCode: "+1868",
  },
  {
    id: "tn",
    name: "Tunisia",
    icon: "https://flagcdn.com/w40/tn.png",
    dialCode: "+216",
  },
  {
    id: "tr",
    name: "Turkey",
    icon: "https://flagcdn.com/w40/tr.png",
    dialCode: "+90",
  },
  {
    id: "tm",
    name: "Turkmenistan",
    icon: "https://flagcdn.com/w40/tm.png",
    dialCode: "+993",
  },
  {
    id: "tv",
    name: "Tuvalu",
    icon: "https://flagcdn.com/w40/tv.png",
    dialCode: "+688",
  },
  {
    id: "ug",
    name: "Uganda",
    icon: "https://flagcdn.com/w40/ug.png",
    dialCode: "+256",
  },
  {
    id: "ua",
    name: "Ukraine",
    icon: "https://flagcdn.com/w40/ua.png",
    dialCode: "+380",
  },
  {
    id: "ae",
    name: "United Arab Emirates",
    icon: "https://flagcdn.com/w40/ae.png",
    dialCode: "+971",
  },
  {
    id: "gb",
    name: "United Kingdom",
    icon: "https://flagcdn.com/w40/gb.png",
    dialCode: "+44",
  },
  {
    id: "us",
    name: "United States",
    icon: "https://flagcdn.com/w40/us.png",
    dialCode: "+1",
  },
  {
    id: "uy",
    name: "Uruguay",
    icon: "https://flagcdn.com/w40/uy.png",
    dialCode: "+598",
  },
  {
    id: "uz",
    name: "Uzbekistan",
    icon: "https://flagcdn.com/w40/uz.png",
    dialCode: "+998",
  },
  {
    id: "vu",
    name: "Vanuatu",
    icon: "https://flagcdn.com/w40/vu.png",
    dialCode: "+678",
  },
  {
    id: "va",
    name: "Vatican",
    icon: "https://flagcdn.com/w40/va.png",
    dialCode: "+379",
  },
  {
    id: "ve",
    name: "Venezuela",
    icon: "https://flagcdn.com/w40/ve.png",
    dialCode: "+58",
  },
  {
    id: "vn",
    name: "Vietnam",
    icon: "https://flagcdn.com/w40/vn.png",
    dialCode: "+84",
  },
  {
    id: "wf",
    name: "Wallis and Futuna",
    icon: "https://flagcdn.com/w40/wf.png",
    dialCode: "+681",
  },
  {
    id: "ye",
    name: "Yemen",
    icon: "https://flagcdn.com/w40/ye.png",
    dialCode: "+967",
  },
  {
    id: "zm",
    name: "Zambia",
    icon: "https://flagcdn.com/w40/zm.png",
    dialCode: "+260",
  },
  {
    id: "zw",
    name: "Zimbabwe",
    icon: "https://flagcdn.com/w40/zw.png",
    dialCode: "+263",
  },
  {
    id: "ax",
    name: "Åland Islands",
    icon: "https://flagcdn.com/w40/ax.png",
    dialCode: "+358",
  },
  {
    id: "aq",
    name: "Antarctica",
    icon: "https://flagcdn.com/w40/aq.png",
    dialCode: "+672",
  },
  {
    id: "bv",
    name: "Bouvet Island",
    icon: "https://flagcdn.com/w40/bv.png",
    dialCode: "+47",
  },
  {
    id: "io",
    name: "British Indian Ocean Territory",
    icon: "https://flagcdn.com/w40/io.png",
    dialCode: "+246",
  },
  {
    id: "tf",
    name: "French Southern Territories",
    icon: "https://flagcdn.com/w40/tf.png",
    dialCode: "+262",
  },
  {
    id: "gf",
    name: "French Guiana",
    icon: "https://flagcdn.com/w40/gf.png",
    dialCode: "+594",
  },
  {
    id: "tf",
    name: "French Southern Territories",
    icon: "https://flagcdn.com/w40/tf.png",
    dialCode: "+262",
  },
  {
    id: "hm",
    name: "Heard Island and McDonald Islands",
    icon: "https://flagcdn.com/w40/hm.png",
    dialCode: "+672",
  },
  {
    id: "kp",
    name: "North Korea",
    icon: "https://flagcdn.com/w40/kp.png",
    dialCode: "+850",
  },
  {
    id: "ps",
    name: "Pale",
    icon: "https://flagcdn.com/w40/ps.png",
    dialCode: "+970",
  },
  {
    id: "pn",
    name: "Pitcairn",
    icon: "https://flagcdn.com/w40/pn.png",
    dialCode: "+64",
  },
  {
    id: "gs",
    name: "South Georgia and the South Sandwich Islands",
    icon: "https://flagcdn.com/w40/gs.png",
    dialCode: "+500",
  },
  {
    id: "sj",
    name: "Svalbard and Jan Mayen",
    icon: "https://flagcdn.com/w40/sj.png",
    dialCode: "+47",
  },
  {
    id: "tk",
    name: "Tokelau",
    icon: "https://flagcdn.com/w40/tk.png",
    dialCode: "+690",
  },
  {
    id: "bl",
    name: "Saint Barthélemy",
    icon: "https://flagcdn.com/w40/bl.png",
    dialCode: "+590",
  },
  {
    id: "mf",
    name: "Saint Martin",
    icon: "https://flagcdn.com/w40/mf.png",
    dialCode: "+590",
  },
  {
    id: "gs",
    name: "South Georgia and the South Sandwich Islands",
    icon: "https://flagcdn.com/w40/gs.png",
    dialCode: "+500",
  },
  {
    id: "sj",
    name: "Svalbard and Jan Mayen",
    icon: "https://flagcdn.com/w40/sj.png",
    dialCode: "+47",
  },
  {
    id: "tk",
    name: "Tokelau",
    icon: "https://flagcdn.com/w40/tk.png",
    dialCode: "+690",
  },
  {
    id: "um",
    name: "United States Minor Outlying Islands",
    icon: "https://flagcdn.com/w40/um.png",
    dialCode: "+1",
  },
  {
    id: "wf",
    name: "Wallis and Futuna",
    icon: "https://flagcdn.com/w40/wf.png",
    dialCode: "+681",
  },
  {
    id: "eh",
    name: "Western Sahara",
    icon: "https://flagcdn.com/w40/eh.png",
    dialCode: "+212",
  },
  {
    id: "ax",
    name: "Åland Islands",
    icon: "https://flagcdn.com/w40/ax.png",
    dialCode: "+358",
  },
  {
    id: "as",
    name: "American Samoa",
    icon: "https://flagcdn.com/w40/as.png",
    dialCode: "+1684",
  },
  {
    id: "ad",
    name: "Andorra",
    icon: "https://flagcdn.com/w40/ad.png",
    dialCode: "+376",
  },
  {
    id: "ai",
    name: "Anguilla",
    icon: "https://flagcdn.com/w40/ai.png",
    dialCode: "+1264",
  },
  {
    id: "aq",
    name: "Antarctica",
    icon: "https://flagcdn.com/w40/aq.png",
    dialCode: "+672",
  },
  {
    id: "ag",
    name: "Antigua and Barbuda",
    icon: "https://flagcdn.com/w40/ag.png",
    dialCode: "+1268",
  },
  {
    id: "am",
    name: "Armenia",
    icon: "https://flagcdn.com/w40/am.png",
    dialCode: "+374",
  },
  {
    id: "aw",
    name: "Aruba",
    icon: "https://flagcdn.com/w40/aw.png",
    dialCode: "+297",
  },
  {
    id: "az",
    name: "Azerbaijan",
    icon: "https://flagcdn.com/w40/az.png",
    dialCode: "+994",
  },
  {
    id: "ug",
    name: "Uganda",
    icon: "https://flagcdn.com/w40/ug.png",
    dialCode: "+256",
  },
  {
    id: "ua",
    name: "Ukraine",
    icon: "https://flagcdn.com/w40/ua.png",
    dialCode: "+380",
  },
  {
    id: "ae",
    name: "United Arab Emirates",
    icon: "https://flagcdn.com/w40/ae.png",
    dialCode: "+971",
  },
  {
    id: "gb",
    name: "United Kingdom",
    icon: "https://flagcdn.com/w40/gb.png",
    dialCode: "+44",
  },
  {
    id: "us",
    name: "United States",
    icon: "https://flagcdn.com/w40/us.png",
    dialCode: "+1",
  },
  {
    id: "uy",
    name: "Uruguay",
    icon: "https://flagcdn.com/w40/uy.png",
    dialCode: "+598",
  },
  {
    id: "uz",
    name: "Uzbekistan",
    icon: "https://flagcdn.com/w40/uz.png",
    dialCode: "+998",
  },
  {
    id: "vu",
    name: "Vanuatu",
    icon: "https://flagcdn.com/w40/vu.png",
    dialCode: "+678",
  },
  {
    id: "ve",
    name: "Venezuela",
    icon: "https://flagcdn.com/w40/ve.png",
    dialCode: "+58",
  },
  {
    id: "vn",
    name: "Vietnam",
    icon: "https://flagcdn.com/w40/vn.png",
    dialCode: "+84",
  },
  {
    id: "ye",
    name: "Yemen",
    icon: "https://flagcdn.com/w40/ye.png",
    dialCode: "+967",
  },
  {
    id: "zm",
    name: "Zambia",
    icon: "https://flagcdn.com/w40/zm.png",
    dialCode: "+260",
  },
  {
    id: "zw",
    name: "Zimbabwe",
    icon: "https://flagcdn.com/w40/zw.png",
    dialCode: "+263",
  },
];

export const uniqueCountriesList = countriesList.filter(
  (country, index, self) => index === self.findIndex((c) => c.id === country.id)
);

export const PostCategories = [
  {
    id: 5,
    name: "animals",
    description: "Animals (Dog, Horse, Tiger, Elephant etc)",
  },
  {
    id: 4,
    name: "culture",
    description:
      "Culture (Arts, Dance, Festivals, Drama, Stage Play, Exhibition etc)",
  },
  {
    id: 3,
    name: "lifestyle",
    description:
      "Lifestyle (Brand, products, Food, Sports, Technology, Living and Architecture etc)",
  },
  {
    id: 2,
    name: "people",
    description:
      "People (Headshots, Action photos and videos, Crowds of people etc)",
  },
  {
    id: 1,
    name: "nature",
    description: "Nature (Sky, Ocean, Trees, Mountains etc)",
  },
];

export const getCountryNameById = (id: string): string | null => {
  const country = countriesList.find((country) => country.id === id);
  return country ? country.name : null;
};
